// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID         string
	SessionID  string
	Role       string
	Content    sql.NullString
	ToolCalls  sql.NullString
	ToolCallID sql.NullString
	Name       sql.NullString
	Model      sql.NullString
	CreatedAt  string
}

type Session struct {
	ID          string
	Channel     string
	ChannelID   sql.NullString
	Title       sql.NullString
	Model       sql.NullString
	Summary     sql.NullString
	SummaryUpTo sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type Turn struct {
	ID           int64
	SessionID    string
	UserMessage  string
	ResponseJson string
	Model        sql.NullString
	CreatedAt    string
}
