// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getSession = `-- name: GetSession :one
SELECT id, channel, channel_id, title, model, summary, summary_up_to, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChannelID,
		&i.Title,
		&i.Model,
		&i.Summary,
		&i.SummaryUpTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnsBySession = `-- name: GetTurnsBySession :many
SELECT id, session_id, user_message, response_json, model, created_at FROM turns WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetTurnsBySession(ctx context.Context, sessionID string) ([]Turn, error) {
	rows, err := q.db.QueryContext(ctx, getTurnsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserMessage,
			&i.ResponseJson,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTurn = `-- name: InsertTurn :exec
INSERT INTO turns (session_id, user_message, response_json, model)
VALUES (?, ?, ?, ?)
`

type InsertTurnParams struct {
	SessionID    string
	UserMessage  string
	ResponseJson string
	Model        sql.NullString
}

func (q *Queries) InsertTurn(ctx context.Context, arg InsertTurnParams) error {
	_, err := q.db.ExecContext(ctx, insertTurn,
		arg.SessionID,
		arg.UserMessage,
		arg.ResponseJson,
		arg.Model,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, channel)
VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET updated_at = datetime('now')
`

type UpsertSessionParams struct {
	ID      string
	Channel string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.ID, arg.Channel)
	return err
}
